#!/bin/sh
set -e

lb config noauto \
    --mode debian \
    --system live \
    --architecture amd64 \
    --distribution trixie \
    --archive-areas "main contrib non-free non-free-firmware" \
    --mirror-bootstrap "https://deb.debian.org/debian/" \
    --mirror-chroot "https://deb.debian.org/debian/" \
    --mirror-chroot-security "https://security.debian.org/debian-security" \
    --mirror-binary "https://deb.debian.org/debian/" \
    --mirror-binary-security "https://security.debian.org/debian-security" \
    --security true \
    --updates true \
    --debian-installer none \
    --bootloaders "grub-pc grub-efi" \
    --binary-images iso-hybrid \
    --chroot-squashfs-compression-type zstd \
    --chroot-squashfs-compression-level 6 \
    --initramfs live-boot \
    --initramfs-compression lzma \
    --apt-recommends false \
    --firmware-chroot true \
    --firmware-binary true \
    --checksums sha256 \
    --uefi-secure-boot auto \
    --ignore-system-defaults \
    --utc-time true \
    --iso-application "KivotOS" \
    --iso-publisher "KivotOS Project" \
    --iso-volume "KivotOS" \
    --image-name "KivotOS" \
    --bootappend-live "boot=live components quiet splash \
	hostname=kivotos \
	username=sensei \
	user-default-groups=audio,cdrom,dip,video,plugdev,netdev,bluetooth,sudo" \
    --memtest none \
    "${@}"
